### ISSUE TITLE
DK2.0 Documentation Changes Log

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#301]
This is a log for tracking changes that will need to be made to the documents to support DK 2.0

*  [x] Confirm vehicle.command.next is witeable - #390 and doc appropriately
* [x] In migrating guide add change from await_params with wait_ready (actually mostly just doc the wai-init when downloading, but also check that wait_ready properly documented in terms of usage in the api ref, parameters and command downloads sections - #408
* [x] Update parameters documentation to explain the stuff about how parameters get populated (e.g. getting all at once or individually, values of parameters before populated. See #404.
* [x] Do a proper write up of connecting behaviour including covering waiting. This should be in our programming guide. 
* [x] Chase up release notes - e.g. 379

 
* [x] Examples
  * [x] Update "Running the examples" doc to cover general instructions
  * [x] Work out standard format for examples to import connect and use an option parser to take in the connection, defaulting to SITL local port
  * [x] Update all examples to use above mechanism and test
  * [x] Update all examples to use vehicle.close
* [x] Document explaining changes and implications of changes vs how to use the API vs v1.x
  * [x] How to import connect and start a connection
  * [x] No MAVProxy so how to connect
  * [x] Passing options to the script now just normal arguments
* [x] Update getting started. 
  * [x] Remove MAVProxy dependencies from getting started.
  * [x] Change back to command line instructions on windows
  * [x] Update the actual dependencies of dk-python (ie remove mavproxy dependencies not needed by dk-python).

* [x] vehicle.close - as per #348 . 
  * [x] add this in the API Ref  
  * [x] add this in the migrating doc.
  * [x] add this in all the examples (done, but in a number of pull requests - not yet in master)
* [x] UPdate **mission_basic.py**, **mission_import_export.py** and **flight_replay.py** examples when [#355](https://github.com/dronekit/dronekit-python/issues/355) is fixed. Both fail. The later says so in the docs and that will need to be tidied. The former does nto.

**Comment by hamishwillee** [comment]
@tcr3dr @mrpollo A few DK2.0 questions you may be able to help with 

* The api object we get back from ``connect()`` - is it a singleton or can we have multiple versions? Or to put it another way, can I now support multiple vehicles in one script
* In examples I shouldn't hardcode the connection so I will need to pass in as an argument. By preference, do you think it is reasonable to default the value to by the SITL local connection or should I always force a connection to be specified?
* We will no longer need our windows installer for MAVProxy. So should we delete the old installer?
* Which of the dependencies are still needed? My feeling is that now we don't *need* mavproxy, then installation on windows becomes easy - just the droneapi and removing dateutil
* We showed connecting to MAVProxy in DK 1.x because that was the default that you had to have. SHould be move to Mission Planner, or have both?

**Comment by tcr3dr** [comment]
@hamishwillee What's the status of this PR? What questions can I help answer?

**Comment by hamishwillee** [comment]
@tcr3dr Nothing. Closing.

I removed the following from scope.  I'd quite like to have done  a programming guide, but in some ways it will be good to settle and see how people use the system. Re the "GCS" section, that would come when we switch to DK-SITL. Still some work there because it doesn't work to use TCP on multiple connections.
* [ ] Create section on using ground stations with DK. MAVProxy, MP or Tower ...
* [ ] System Overview, with diagrams
* [ ] Create Programming guide - #397
